### ISSUE TITLE
[Feature Request] Add support for darwin-arm64

### ISSUE THREAD

**Issue by n-rodriguez** [gasuketsu/asdf-tokei#4]
Thank you!

**Comment by gasuketsu** [comment]
Thanks for raising feature request.

Currently there is no darwin-arm64 asset in tokei releases.
When darwin-arm64 asset is ready in upstream I will add support for it.

Thanks.

**Comment by n-rodriguez** [comment]
> Currently there is no darwin-arm64 asset in tokei releases.

Yep, there is an issue https://github.com/XAMPPRocky/tokei/issues/724

**Comment by n-rodriguez** [comment]
And there is a pre release : https://github.com/XAMPPRocky/tokei/releases/tag/v13.0.0-alpha.0

**Comment by n-rodriguez** [comment]
For now it uses `tokei-x86_64-apple-darwin.tar.gz` archive :

```sh
nicolas@MacBook-Pro-de-Nicolas:~/.asdf/installs/tokei/13.0.0-alpha.0/bin$ file tokei
tokei: Mach-O 64-bit executable x86_64
```

and it works :)

```sh
nicolas@MacBook-Pro-de-Nicolas:~/.asdf/installs/tokei/13.0.0-alpha.0/bin$ ./tokei --version
tokei 13.0.0-alpha.0 compiled with serialization support: json, cbor, yaml
```
